# Site settings
# These are used to personalize your new site.
title: Alena N. Durel # your name here
logo: "/images/circle_pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science and Cybersecurity (class of 2024)
  <br /><br />
  <a href="https://docs.google.com/document/d/1IIqE4yZblef18q0v1RkA1OZnsqQHlwNbtqY_mYb4TmM/edit?usp=sharing">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/alena-durel/">View My LinkedIn Profile</a>
repository: "alenanicole/alenanicole.github.io"
github_username:  alenanicole # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

